import { setLockPackageVersion, setPackageVersion } from '@/lib/toml.js'
import { describe, expect, it } from 'vitest'

const MANIFEST = [
  '# Top comment',
  '[package]',
  'name = "demo"',
  'version = "0.1.0"',
  'edition = "2021"',
  '',
  '[dependencies]',
  'serde = { version = "0.1.0", features = ["derive"] }',
  '',
  '[dependencies.other]',
  'version = "0.1.0"',
  '',
].join('\n')

const LOCK = [
  '# This file is automatically @generated by Cargo.',
  'version = 3',
  '',
  '[[package]]',
  'name = "serde"',
  'version = "1.0.210"',
  '',
  '[[package]]',
  'name = "demo"',
  'version = "0.1.0"',
  '',
].join('\n')

describe('setPackageVersion', () => {
  it('returns the package name and current version', () => {
    const result = setPackageVersion(MANIFEST, '1.0.0')

    expect(result.name).toBe('demo')
    expect(result.current).toBe('0.1.0')
  })

  it('changes only the [package] version line', () => {
    const result = setPackageVersion(MANIFEST, '1.0.0')

    expect(result.text).toBe(
      MANIFEST.replace(
        'version = "0.1.0"\nedition',
        'version = "1.0.0"\nedition'
      )
    )
  })

  it('leaves dependencies sharing the same version untouched', () => {
    const result = setPackageVersion(MANIFEST, '1.0.0')

    expect(result.text).toContain('serde = { version = "0.1.0"')
    expect(result.text).toContain('[dependencies.other]\nversion = "0.1.0"')
  })

  it('preserves spacing, quote style and trailing comments', () => {
    const text =
      '[package]\nname = "demo"\nversion    = \'0.1.0\'   # release\n'
    const result = setPackageVersion(text, '2.0.0')

    expect(result.text).toBe(
      '[package]\nname = "demo"\nversion    = \'2.0.0\'   # release\n'
    )
  })

  it('handles versions containing regex characters', () => {
    const text = '[package]\nname = "demo"\nversion = "1.0.0+build.1"\n'
    const result = setPackageVersion(text, '2.0.0')

    expect(result.current).toBe('1.0.0+build.1')
    expect(result.text).toContain('version = "2.0.0"')
  })

  it('throws when there is no [package] table', () => {
    expect(() =>
      setPackageVersion('[workspace]\nmembers = ["a"]\n', '1.0.0')
    ).toThrow('No [package] table found in the manifest')
  })

  it('throws when the version is inherited from the workspace', () => {
    expect(() =>
      setPackageVersion(
        '[package]\nname = "demo"\nversion.workspace = true\n',
        '1.0.0'
      )
    ).toThrow('an inherited version cannot be patched')
  })

  it('throws when the name is missing', () => {
    expect(() =>
      setPackageVersion('[package]\nversion = "0.1.0"\n', '1.0.0')
    ).toThrow('No name string found in the [package] table')
  })

  it('throws on invalid toml', () => {
    expect(() => setPackageVersion('[package\nname = "x"\n', '1.0.0')).toThrow()
  })
})

describe('setLockPackageVersion', () => {
  it('returns the current version of the named package', () => {
    const result = setLockPackageVersion(LOCK, 'demo', '1.0.0')

    expect(result.current).toBe('0.1.0')
  })

  it('changes only the matching package entry', () => {
    const result = setLockPackageVersion(LOCK, 'demo', '1.0.0')

    expect(result.text).toBe(
      LOCK.replace(
        'name = "demo"\nversion = "0.1.0"',
        'name = "demo"\nversion = "1.0.0"'
      )
    )
  })

  it('leaves the lock file format version untouched', () => {
    const result = setLockPackageVersion(LOCK, 'demo', '1.0.0')

    expect(result.text).toContain('version = 3')
  })

  it('leaves other packages untouched', () => {
    const result = setLockPackageVersion(LOCK, 'demo', '1.0.0')

    expect(result.text).toContain('name = "serde"\nversion = "1.0.210"')
  })

  it('patches a package that comes before others', () => {
    const result = setLockPackageVersion(LOCK, 'serde', '2.0.0')

    expect(result.current).toBe('1.0.210')
    expect(result.text).toContain('name = "serde"\nversion = "2.0.0"')
    expect(result.text).toContain('name = "demo"\nversion = "0.1.0"')
  })

  it('throws when the package is absent', () => {
    expect(() => setLockPackageVersion(LOCK, 'missing', '1.0.0')).toThrow(
      'Package "missing" not found in the lock file'
    )
  })

  it('throws when there are no [[package]] entries', () => {
    expect(() =>
      setLockPackageVersion('version = 3\n', 'demo', '1.0.0')
    ).toThrow('No [[package]] entries found in the lock file')
  })
})
